### ISSUE TITLE
Custom transit handlers

### ISSUE THREAD

**Issue by usernolan** [macchiato-framework/macchiato-core#30]
What is the recommended way to use [custom transit handlers](https://github.com/cognitect/transit-cljs/wiki/Getting-Started#writing-custom-values)?

I'd be happy to help out if there is no current support. I have a few ideas around modifying wrap-restful-format which I think could be pretty simple. Let me know if you have any thoughts on what would be best and I can work on a PR.

Apologies if I'm missing something. Thanks for all your great work on Macchiato so far.

**Comment by yogthos** [comment]
Ah yeah I don't think that's working yet. A PR would be very welcome, and modifying wrap-restful-format would definitely be the way to go here.

**Comment by usernolan** [comment]
Addressed in #31. Will close for now but feel free to reopen if anything comes up.
