### ISSUE TITLE
"Buffer() is deprecated due to security and usability issues" in macchiato.middleware.session.cookie

### ISSUE THREAD

**Issue by theasp** [macchiato-framework/macchiato-core#41]
```
(node:12627) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

See: https://nodejs.org/en/docs/guides/buffer-constructor-deprecation/

**Comment by yogthos** [comment]
Thanks for the heads up, any chance you could do a PR for this? :)

**Comment by jdhorwitz** [comment]
I will take a look at this one as well.  Thanks @theasp .

**Comment by jdhorwitz** [comment]
This looks like it was fixed with https://github.com/macchiato-framework/macchiato-core/commit/1144c9e2f5f91e7d390bb38f751810e295388332 After @yogthos confirms, I think we can resolve this one.

**Comment by yogthos** [comment]
Yup, that does look like it's been fixed.
