### ISSUE TITLE
Macchiato is broken in :advanced compilation with Shadow-cljs

### ISSUE THREAD

**Issue by pavel-klavik** [macchiato-framework/macchiato-core#44]
The following line is broken when compiled in :advanced mode (default for the release mode in Shadow-cljs):

```clojure
(.createServer (node/require "http") http-handler)
```

Getting the following error:

```
(intermediate value)(intermediate value)(intermediate value).rd is not a function
```

**Comment by yogthos** [comment]
Is there a reason to do advanced compilation since the code is running server side?

**Comment by pavel-klavik** [comment]
For my small case probably no. But it is the default mode in Shadow-cljs, so there is a reason: faster execution, smaller file size, etc. As I understand, requiring http in a different way would solve this problem. Anyway, supporting Shadow-cljs out of the box sounds like a good idea.

**Comment by yogthos** [comment]
Yeah I agree with shadow-cljs support, would you be up for doing a PR for the fix?

**Comment by pavel-klavik** [comment]
I don't think I have good enough understanding of NodeJS and how other compilation works to know the solution for this.

**Comment by yogthos** [comment]
No worries, myself or @jdhorwitz will try take a look in the near future.

**Comment by jdhorwitz** [comment]
I can start to take a look at this.  Thanks for reporting @pavel-klavik !

**Comment by yogthos** [comment]
👍

**Comment by jdhorwitz** [comment]
Starting back on this, work got crazy!

**Comment by yogthos** [comment]
No worries, life has a habit of getting in the way of open source. :)

**Comment by mraveloarinjaka** [comment]
Hello,
There are several parts of the code that break in release mode.
Will you be against adding a dependency to https://github.com/applied-science/js-interop ?
I think this should work if all the interop is handled via that library.
I can try to implement that if you are ok with the additional dependency.

**Comment by yogthos** [comment]
Sure, that sounds good to me. I can make the release if you'd like to do a PR for the update.

**Comment by mraveloarinjaka** [comment]
actually I was able to do without the dependency. I am sending the PR

**Comment by mraveloarinjaka** [comment]
https://github.com/macchiato-framework/macchiato-core/pull/47 created

**Comment by yogthos** [comment]
thanks, merged
