### ISSUE TITLE
cors/header-name is calling a non-existing (deprecated and then removed) "capitalize" function from Cuerdas lib

### ISSUE THREAD

**Issue by uds** [macchiato-framework/macchiato-core#52]
Function _capitalize_ (from https://github.com/funcool/cuerdas library) was deprecated and replaced with _capital_.
And then _capitalize_ was removed from Cuerdas lib with the version 2020.03.26.

Here is a call to that non-existing _capitalize_ function: 
https://github.com/macchiato-framework/macchiato-core/blob/893832b5c8477b591822b8cf56b9584c5c4d8efd/src/macchiato/middleware/cors.cljs#L78

**Comment by yogthos** [comment]
thanks, updated the call to use `capital`
